[package]
name = "rongo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = '0.15.1'
mongodb = '2.2.1'
tokio = "1.18.1"
